version: "3.9"
volumes:
  slamint:
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: ["start-dev" ,"--http-port=8080", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: sla_mint
      POSTGRES_PASSWORD: P@ssword1
      POSTGRES_DB: sla_mint
    ports: ["5432:5432"]
    volumes: [slamint:/var/lib/postgresql/data]