packages:
  - 'api/*'
  - 'common/*'
  - '@slamint/*'
autoInstallPeers: true
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - 'esbuild'
  - 'nx'
  - 'unrs-resolver'
strictPeerDependencies: false
