packages:
  - api/*
  - common/*
autoInstallPeers: true
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - nx
  - unrs-resolver
strictPeerDependencies: false
