packages:
  - api/*
  - common/*
  - '@slamint/*'
  - web/*
autoInstallPeers: true
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - nx
  - unrs-resolver
strictPeerDependencies: false
