// common/core/src/config/config.keys.ts
export enum ConfigKey {
  NODE_ENV = 'NODE_ENV',

  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USER = 'DB_USER',
  DB_PASS = 'DB_PASS',
  DB_NAME = 'DB_NAME',

  KEYCLOAK_REALM = 'KEYCLOAK_REALM',
  KEYCLOAK_AUTH_SERVER_URL = 'KEYCLOAK_AUTH_SERVER_URL',
  KEYCLOAK_CLIENT_ID = 'KEYCLOAK_CLIENT_ID',
  KEYCLOAK_CLIENT_SECRET = 'KEYCLOAK_CLIENT_SECRET',
}
