export enum ConfigKey {
  NODE_ENV = 'NODE_ENV',

  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USER = 'DB_USER',
  DB_PASS = 'DB_PASS',
  DB_NAME = 'DB_NAME',

  KEYCLOAK_REALM = 'KEYCLOAK_REALM',
  KEYCLOAK_AUTH_SERVER_URL = 'KEYCLOAK_AUTH_SERVER_URL',
  KEYCLOAK_CLIENT_ID = 'KEYCLOAK_CLIENT_ID',
  KEYCLOAK_CLIENT_SECRET = 'KEYCLOAK_CLIENT_SECRET',

  USER_MS_HOST = 'USER_MS_HOST',
  USER_MS_PORT = 'USER_MS_PORT',

  OIDC_ISSUER = 'OIDC_ISSUER',
  OIDC_CLIENT = 'OIDC_CLIENT',
}
