export enum ConfigKey {
  NODE_ENV = 'NODE_ENV',
  APP_URL = 'APP_URL',
  // Databases and Cache Store
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USER = 'DB_USER',
  DB_PASS = 'DB_PASS',
  DB_NAME = 'DB_NAME',
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_PASSWORD = 'REDIS_PASSWORD',
  // Keycloak
  KEYCLOAK_REALM = 'KEYCLOAK_REALM',
  KEYCLOAK_SERVER_URL = 'KEYCLOAK_SERVER_URL',
  OIDC_ISSUER = 'OIDC_ISSUER',
  OIDC_CLIENT = 'OIDC_CLIENT',
  OIDC_JWKS_URI = 'OIDC_JWKS_URI',
  OIDC_SVC_CLIENT = 'OIDC_SVC_CLIENT',
  OIDC_SVC_CLIENT_SECRET = 'OIDC_SVC_CLIENT_SECRET',
  // Microservices Configuration
  GATEWAY_HOST = 'GATEWAY_HOST',
  GATEWAY_PORT = 'GATEWAY_PORT',
  ACCMGMT_MS_HOST = 'ACCMGMT_MS_HOST',
  ACCMGMT_MS_PORT = 'ACCMGMT_MS_PORT',
}
